### PR TITLE
Make IndexedDB optional & code refactor

### PR DESCRIPTION
**Pull request by s314cy**
This PR includes the following changes:
* "Fast build" button at the home page, below the regular "Start building" button
* Going into fast build turns off IndexedDB for the rest of training.
* With IndexedDB turned off, the model is created and loaded in a variable by the training manager on training, i.e. at the very last moment
* With IndexedDB turned on, the model is initialized in IndexedDB by the description frame, then loaded in a variable by the training manager on training.
* The model library is not shown when IndexedDB is turned off.
* Renamed src/helpers/my_memory/indexeddb_script.js to src/helpers/memory/helpers.js
* All IndexedDB calls now go through memory/helpers.js
* Largely simplified the calls to IndexedDB, only using the TFJS library (no IndexedDB transaction).
* In IndexedDB, working models are stored in the working/ folder, whereas saving a working model stores it into the saved/ folder. This replaces the working_ and saved_ prefixes.

Since I brought modifications to the training manager, I also made the following tweaks:
* Moved Vue environment calls in the training manager to the training components, to better separate the UI from the logic.
* The training manager now takes a task object as attribute.
* Moved the functions in src/helpers/training/training_script.js to the training manager
* Removed src/helpers/training/training_script.js

I will propagate the changes brought by my recent PRs to DeAI by next Friday, so that my code doesn't conflict with Lucas's ongoing PR over there :)

### CODE REVIEW

**Comment by martinjaggi** [comment]
excellent. 
- the switch for with or without indexDB could maybe be moved to the settings page instead of the start page?
- do you think we could turn it of always, except when save/load from the model library is used?

**Comment by s314cy** [comment]
> excellent.
> 
>     * the switch for with or without indexDB could maybe be moved to the settings page instead of the start page?
> 
>     * do you think we could turn it of always, except when save/load from the model library is used?

1. Sure then it would be hot switchable, right? We just have to ensure everything is robust. Typically, I think (1) => (2).
2. You mean removing the "working model" way of doing things? I do think it is a bit weird, since the user has no way to access this model. Indeed, there is no recovery mode after reopening the window (e.g. to resume training with the previous working model), one can only load a previously manually saved model. Also, the model has to be loaded into browser memory at some point anyway, so it doesn't help with the training of multiple tasks at once either. Hence I agree it is desirable to remove the working model. This would force the description frame and its "load previously saved model" feature to pass information up to the training frame/manager. The training manager would then either load a fresh model from server (just like it would do with IndexedDB off) or load the previously saved model.

**Comment by s314cy** [comment]
I'm going with the following guidelines:
* Make IndexedDB hot switchable in the settings
* Allow the user to recover the last working model (hence keep the "working model" way of doing things)
* Allow the user to load a saved model from the model library into the current working model
* Save the working model after each epoch, instead of after training only
* Make these features robust relative to current training

By the way, IndexedDB is already always "turned off", i.e. the code compiles even if IndexedDB is not available, and runtime problems are avoided by checking whether or not IndexedDB is turned on before making any calls to helpers/memory/helpers.js. Note: IndexedDB can be turned on iff it is both active in the settings and available in the browser.

**Review by Nacho114 — APPROVED** [review]
Tested and working, code seems ok too.

**Comment by s314cy** [comment]
I will make a few last changes to the UI to make the turn off of IndexedDB more user-friendly. Then I will merge this PR and #24.

**Pull request merged**
